service: coughona-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  environment:
    AWS_ACCESS_KEY_ID: ${file(./serverless.env.yml):prod.AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${file(./serverless.env.yml):prod.AWS_SECRET_ACCESS_KEY}

plugins:
  - serverless-plugin-typescript-express
  - serverless-offline

functions:
  health:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: get
  app:
    handler: dist/index.handler
    events:
      - http:
          path: /upload
          method: post
